language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - make > make-log.txt
  - git config --global user.name "upupming"
  - git config --global user.email "upupming@gmail.com"
  - git add images training_results
  - git commit -m "Built images & training results with travis-ci"
  - git push ${GH_REF}

env: 
 global:
   - GH_REF: https://${GH_TOKEN}@github.com/upupming/Lab1-polynomial-curve-fitting.git 